file1 = open('rw_bonus', 'w+')
file1.write("aaaaa\nbbbbb\ncccccc\nddddd")
file1.seek(0)
print(file1.read())

file1.seek(0)
file_begin = file1.tell()
print(file_begin)
file1.seek(0,2)
file_end = file1.tell()
print(file_end)
file1.seek((file_begin + file_end)/2)
file1.write("eeeeee\n")
file1.seek(0)
print(file1.read())
